FROM python:3.7-slim-buster

WORKDIR /app

RUN mkdir -p /postgres_data

ENV PYTHONDONTWRITEBITECODE 1

ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apt-get update \
   && apt-get -y install netcat gcc postgresql \
   && apt-get clean

# Setup GDAL
RUN apt-get update &&\
   apt-get install -y binutils libproj-dev gdal-bin python-gdal python3-gdal 

# Setup GDAL
RUN apt-get update &&\
   apt-get install -y binutils libproj-dev gdal-bin python-gdal python3-gdal 

# copy requirements to the image
COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

# Copy over the project
COPY . /app