# Generated by Django 3.1.5 on 2021-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.IntegerField(default=0, verbose_name='School Code'),
        ),
    ]
